version: '3.2'

networks:
  trino-cluster:
    # name: trino-cluster
    driver: bridge

services:
  coordinator:
    image: "detective/trino-coordinator" # :${TRINO_VERSION}
    ports:
      - "8080:8080"
    container_name: "coordinator"
    volumes:
      - ./mount/etc/catalog:/usr/local/trino/etc/catalog
    networks:
      - trino-cluster
    command: http://coordinator:8080 coordinator
  worker0:
    image: "detective/trino-worker" # :${TRINO_VERSION}
    container_name: "worker0"
    ports:
      - "8081:8081"
    volumes:
      - ./mount/etc/catalog:/usr/local/trino/etc/catalog
    networks:
      - trino-cluster
    command: http://coordinator:8080 worker0

  worker1:
    image: "detective/trino-worker" # :${TRINO_VERSION}
    container_name: "worker1"
    ports:
      - "8082:8081"
    volumes:
      - ./mount/etc/catalog:/usr/local/trino/etc/catalog
    networks:
      - trino-cluster
    command: http://coordinator:8080 worker1