version: "3.9"

services:

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    build:
      context: .
      dockerfile: dockerfile
      target: base
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"