name: Tests
env:
  SQL_DATABASE: testdb
  SQL_USER: test_user
  SQL_PASSWORD: test
  MYSQL_HOST: mysql-master
  POSTGRES_HOST: postgres
  NODE_ENV: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9']
    services:
      mysql-master:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.SQL_DATABASE }}
          MYSQL_USER: ${{ env.SQL_USER }}
          MYSQL_PASSWORD: ${{ env.SQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.SQL_PASSWORD }}
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DATABASE: ${{ env.SQL_DATABASE }}
          POSTGRES_USER: ${{ env.SQL_USER }}
          POSTGRES_PASSWORD: ${{ env.SQL_PASSWORD }}
          POSTGRES_ROOT_PASSWORD: ${{ env.SQL_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mssql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          MSSQL_DATABASE: ${{ env.SQL_DATABASE }}
          MSSQL_USER: ${{ env.SQL_USER }}
          MSSQL_PASSWORD: ${{ env.SQL_PASSWORD }}
          MSSQL_ROOT_PASSWORD: ${{ env.SQL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo su
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/21.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
          exit
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc
          sudo apt-get install -y unixodbc-dev
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
